<?php

namespace Database\Seeders;

use App\Models\AvatarAsset;
use Illuminate\Database\Seeder;

class AvatarAssetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $assets = [
            [
              "type" => "Hairstyles",
              "name" => "h1",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "0jEQWAmXqz35RQ2gWQUuGb0wM64nGLx5DxijXt3m.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h2",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "Gi1VqGJVlSf0jddnaV7E59dlxvXAIbCbUWelglyw.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h3",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "he4s3ganVMHYNh5bQgkkOmeZ3t9VCE1KV4prViHG.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h4",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "xXrGDiX4Dd66ycFK1EtUqOv9lXa5NV4yWo1mpK51.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h5",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "hEFuNAm7U7ZLX90mW2Cr2Q3XizDoUIsJvVWg6eh3.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h6",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "RHYgPSrOTYwFcdl8fHxUatgxfgcQC1U1Si9pghBf.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h7",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "J2aTq6th22Zc6uUkZ33LIVtNeFgz7xvoOYSxgQ6Q.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h8",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "9z2fmPAYvRbjt1Wvz7A39LY6FudpeLd0d7EYwabN.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h9",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "bs1BsgavPFjjckPPCKjCf2zTiR0vNtKAm0tQWNMh.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h10",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "Cw4vHtRk60lwmUZr4Af17TTcoZs1jWDw6OtcrAqW.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h12",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "B52cke7tIXNalNHTmh3MwzSnBfqWowyjIzuAaeDF.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h13",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "sYdPHilHkFiSjcmoKmFapYtFIloo2GdymQM6Dp8u.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h14",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "7EvhC5RLrIyjpcRfSnswJji67OlurUblVuj0ll8I.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h15",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "VWq0ZwP0Ul35bvfrVi6ny6Q2HDXOMWikCInr9E50.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h16",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "NJcyO8II9F5v37w29qlsOrHI54tr8FPRxdM6lK4b.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h17",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "cfN3rwVmObY5BHqxHKkqq3y2HLiSs9p1Axtpl3SP.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h18",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "Z18Fc3KHu3nX2cmrgtSUS4r191vzKsOfkzXRrnb5.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h19",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "KlyOSkhJObH57CsJw0ZVHgkXuiYwL5wsUaE8QpzU.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h20",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "nmoYGzPbixKMuFD9ghMsLLcqw7gBMkj1p2cH89Ie.png",
            ],
            [
              "type" => "Clothes",
              "name" => "Pberkelyjockgirl1",
              "for_premium" => 1,
              "gender" => "Female",
              "college" => "Berkeley Business And Science",
              "cost" => "0",
              "cost_type" => null,
              "path" => "tCDjPHTjmnhX7dpxpGufcyJMlJT2cInQ7QN3wEBm.png",
            ],
            [
              "type" => "Clothes",
              "name" => "PIScheerleader5",
              "for_premium" => 1,
              "gender" => "Female",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "SjMDGyHO3Le7O7uNlo6IALN5exJhL8WFmCEG5HRK.png",
            ],
            [
              "type" => "Clothes",
              "name" => "PIScheerleaderlongsleeves",
              "for_premium" => 1,
              "gender" => "Female",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "Xb9GpxrqV1JeLQPPQp1y1ys1jTR8NRTJy660JbLq.png",
            ],
            [
              "type" => "Clothes",
              "name" => "Preagancheerleaderlongsleeves",
              "for_premium" => 1,
              "gender" => "Female",
              "college" => "Reagan Arts And Humanities",
              "cost" => "0",
              "cost_type" => null,
              "path" => "sWqx2RtsDUUvETiUKSpOF2wYwW5AHFPihXpoYNBr.png",
            ],
            [
              "type" => "Clothes",
              "name" => "Preagancheerleadersleeveless",
              "for_premium" => 1,
              "gender" => "Female",
              "college" => "Reagan Arts And Humanities",
              "cost" => "0",
              "cost_type" => null,
              "path" => "Cq3MFSb9Odsqkq5VILtEwFF3n6A4kg9CbgEtwu4c.png",
            ],
            [
              "type" => "Clothes",
              "name" => "Preaganjockgirl",
              "for_premium" => 1,
              "gender" => "Female",
              "college" => "Reagan Arts And Humanities",
              "cost" => "0",
              "cost_type" => null,
              "path" => "EzbVgu8DCs5lN9qnggSnSQ6Rv1bGmomXMMushSzj.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rberkelycoat2",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Berkeley Business And Science",
              "cost" => "0",
              "cost_type" => null,
              "path" => "r4RTGuuUzrRBCpTgDbtlL0Y0XMgLCQPOTqlrx9p0.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rberkelyshortsleeves1",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Berkeley Business And Science",
              "cost" => "0",
              "cost_type" => null,
              "path" => "xeWOStI89rWwkIWyVK62aDmLPmojUDKL67PGpD1A.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rberkelyshortsleeves3",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Berkeley Business And Science",
              "cost" => "0",
              "cost_type" => null,
              "path" => "2KDXGTzBdmTQciXrbQBxokmCeTMiYgHWDcZp92fO.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rberkelyvest",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Berkeley Business And Science",
              "cost" => "0",
              "cost_type" => null,
              "path" => "TndG5D53lGZ72S3r4EcXmZjN19U6Z53XtTVajwEw.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rberlongsleeveswithoutvest",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Berkeley Business And Science",
              "cost" => "0",
              "cost_type" => null,
              "path" => "aFotNz6Ddl1qIqNkG1Jg0zRgssxTaeYBZxhWgBmt.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rberpe",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Berkeley Business And Science",
              "cost" => "0",
              "cost_type" => null,
              "path" => "cnu8AHZTCz4nqJcnRXfU0FZ7Aaf9zKn7SyjyKjCk.png",
            ],
            [
              "type" => "Clothes",
              "name" => "risgirl1",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "NgysCUtHtvw0v8y8gpP1zol1MxjEPvA2K5icTLxz.png",
            ],
            [
              "type" => "Clothes",
              "name" => "risgirl3",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "j73aHWYyL7xqGbpJdkwFis0cVlU43H8ukO1W6GJJ.png",
            ],
            [
              "type" => "Clothes",
              "name" => "risgirl5",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "EFCvov1icmEqn9hjdXoDehZwrCO7x6FBYX9tHV58.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rispi",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "YBx2QfAQcktI9Trdk30NrXi1DC8VWr2moKRrDUxI.png",
            ],
            [
              "type" => "Clothes",
              "name" => "risshortsleeves",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "chPfBSabwg6ncjOVVAhCWqQHLDebb5pT10AIaEvQ.png",
            ],
            [
              "type" => "Clothes",
              "name" => "risshortsleeveswithvest",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "uaxNEUgDpmfQgrFYpFt3BG0NWHG9OYkqU7yHYdCk.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rreagan1",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Reagan Arts And Humanities",
              "cost" => "0",
              "cost_type" => null,
              "path" => "OvGOUJhlZxG3MgcZsq7JAeNxCm3NEh5LqOotT5PR.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rreagan2",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Reagan Arts And Humanities",
              "cost" => "0",
              "cost_type" => null,
              "path" => "875lVJzS3G6OUsrsobyiIOPxTOdA6HMWDh7jCRbo.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rreagan3",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Reagan Arts And Humanities",
              "cost" => "0",
              "cost_type" => null,
              "path" => "wrY046UwvMyRu8jIxiS4SxLVfC5sL5C8q9Z3ZXMx.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rrepe",
              "for_premium" => 0,
              "gender" => "Female",
              "college" => "Reagan Arts And Humanities",
              "cost" => "0",
              "cost_type" => null,
              "path" => "y2ekbgsyFI4Fm9d9PgGgA8AzRz65JfjYrddjfTut.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h1",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "hNu1Rtf17n9KlJLBbt2A1DP2X5IUthX5J96Tm5fc.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h2",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "kkaa9DUzh9qP90caKQaTr3Fgr9vXwiNtoLmLeKhn.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h3",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "1RY59G9Op8pX24QKzljMw97GKiPBPusaNa2eZH0X.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h4",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "6LBdmn6YIMJbZJhA4UcepN4obXvhUAHJLKH0CjqT.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h5",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "hVdPGPnhPtKw9H2rfGL9yGBt6bGxYKXfNmKksKcP.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h6",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "R60kozNfbY4TTDV5JIA8CvV5JSz1YZ6A7TUbgUOy.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h7",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "gRFvmElyXgC0ZXIau9YBJ2jeewVoD3LbARM0W1Jd.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h8",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "lsi9yQvwv7wCbk4tENWdOJGNVhInacRkcjJTmQMD.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h9",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "Dms9ZLpaUh4h7lqTqHS504w27MmTCNAxvlZkwQUY.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h10",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "yOdY9RvgXzuXkapiwQWBdV4302WoMUvU3cE5RMKd.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h11",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "oYSfEIqZdik97x7fVrw20wvA3Xy5BDzzf9FqR1aC.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h12",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "8NZnv294N4RjyXbZLV5SdA1q1TPZQ9MvL61zwhm8.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h14",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "9DnJ2N1VC6Iist6TTFPjR8XCGAXBkbNL1fP6d8Tz.png",
            ],
            [
              "type" => "Hairstyles",
              "name" => "h15",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "All",
              "cost" => "0",
              "cost_type" => null,
              "path" => "n52cFmWEXiRqkeXkXrYHODTHlTZbeuMUmfXYm7A4.png",
            ],
            [
              "type" => "Clothes",
              "name" => "jockboy",
              "for_premium" => 1,
              "gender" => "Male",
              "college" => "Berkeley Business And Science",
              "cost" => "0",
              "cost_type" => null,
              "path" => "6fbs2dwdbopq2B9C9NRHboJ1IuzZpd7VDHBeZabc.png",
            ],
            [
              "type" => "Clothes",
              "name" => "pischeerleader",
              "for_premium" => 1,
              "gender" => "Male",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "0V03NLeWYKPYtGl1WYhObDRqKDKFUMWX9ldFx44B.png",
            ],
            [
              "type" => "Clothes",
              "name" => "pischeerleaderboywithpopoms",
              "for_premium" => 1,
              "gender" => "Male",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "TfpK8OtmFCLhFwuqwCHYksOW7GeQn8o0y69SClB4.png",
            ],
            [
              "type" => "Clothes",
              "name" => "raeganjockboy",
              "for_premium" => 1,
              "gender" => "Male",
              "college" => "Reagan Arts And Humanities",
              "cost" => "0",
              "cost_type" => null,
              "path" => "8F7cQQBA9P7Q3CngEbOd58Fcpx3drNh50EkFWwHc.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rberkelyboylongsleeves",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Berkeley Business And Science",
              "cost" => "0",
              "cost_type" => null,
              "path" => "o38LAenqD28k6UU8bWoiZxhXyTjpfpgwg2BdGJiu.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rberkelycoatboy",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Berkeley Business And Science",
              "cost" => "0",
              "cost_type" => null,
              "path" => "tiwzi75NigeyFY35ItPCbclfPsvzReWuAz4qptjw.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rberkelylongsleeveswithvestboy",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Berkeley Business And Science",
              "cost" => "0",
              "cost_type" => null,
              "path" => "tjY6vwVpvB4BdPTRJewWf1p7fn3nxc2Mj1K7Qy4f.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rberkelypeboy1",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Berkeley Business And Science",
              "cost" => "0",
              "cost_type" => null,
              "path" => "FgEFh7MUfSO0x4f4ALxAVc9cIP6GmgOMihCB5AXP.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rberkelyshortsleevesboy",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Berkeley Business And Science",
              "cost" => "0",
              "cost_type" => null,
              "path" => "i9BEvr0FEFl47uB7x3OlMrGGzVsSyG8Nkp4qvxGV.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rberkelyshortsleeveswithvestboy",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Berkeley Business And Science",
              "cost" => "0",
              "cost_type" => null,
              "path" => "SSbZf8uyecMmKLgOqEHTMefS6kfyfYNQZDBD9PG6.png",
            ],
            [
              "type" => "Clothes",
              "name" => "reaganpeboy",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Reagan Arts And Humanities",
              "cost" => "0",
              "cost_type" => null,
              "path" => "dN02xnr6yzxWrsHTM5pXnsKOUNrn8XoiJDakdl6n.png",
            ],
            [
              "type" => "Clothes",
              "name" => "risboyincoat",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "q9JqkjA0NkYpftoSyLJUfh8jbOaaUxZKRRHqjHWV.png",
            ],
            [
              "type" => "Clothes",
              "name" => "risboyinpoloshirt",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "gzZXNYwSKElFsmoavKHuQnwcoKKi4uW0bY4GOXKJ.png",
            ],
            [
              "type" => "Clothes",
              "name" => "risboyinvest",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "zQpiWJd4oD6g7olW2bLJcC9pam9Md5P4vFhZ0M45.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rispeboy1",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "67jRCtC7LS8kkpHWAmCRxSoHiio612aZAebvpjpe.png",
            ],
            [
              "type" => "Clothes",
              "name" => "risshortsleevesboy1",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "tr6pbVLRVwjvoBr5AQSZqNPzwboZZ3Epv1W3QMfj.png",
            ],
            [
              "type" => "Clothes",
              "name" => "risshortsleeveswithvestboy1",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Integrated School",
              "cost" => "0",
              "cost_type" => null,
              "path" => "FnutnqZvPLv4yNAohyVzpFHx1yzlLAmFB7KPX9fV.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rraegan",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Reagan Arts And Humanities",
              "cost" => "0",
              "cost_type" => null,
              "path" => "PDJpuM4suiPWCmKiATtjkaNwXtLwhnd9bd5oC3kd.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rraegancheerleader2withoutpoms",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Reagan Arts And Humanities",
              "cost" => "0",
              "cost_type" => null,
              "path" => "jCH6bfLmMfwfTMRene3cjodlfupQrElXcEdAdlqM.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rraegancheerleaderwithpomboy",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Reagan Arts And Humanities",
              "cost" => "0",
              "cost_type" => null,
              "path" => "O0dPRBxEyh1qmSJYVEfjrWIYEjV6x76bjq9INmyt.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rraeganshortsleevesboy1",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Reagan Arts And Humanities",
              "cost" => "0",
              "cost_type" => null,
              "path" => "wPyxpRPEtE6z2CIZAK1GtQLCLMuTiDqyRBUNoemG.png",
            ],
            [
              "type" => "Clothes",
              "name" => "rraeganvest",
              "for_premium" => 0,
              "gender" => "Male",
              "college" => "Reagan Arts And Humanities",
              "cost" => "0",
              "cost_type" => null,
              "path" => "gb9wF8lmPfahJNjP8SW82WPBOXq5dCEfp4RuRGbn.png",
            ],
          ];
          foreach ($assets as $asset) {
              AvatarAsset::create($asset);
          }
    }
}
