<?php

namespace App\Nova;

use App\Nova\Actions\GenerateNewAan;
use App\Nova\Actions\SendEmail;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\Badge;
use Laravel\Nova\Fields\BelongsTo;
use Laravel\Nova\Fields\Date;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;

class Aan extends Resource
{
    public static $group = 'user Management';

    public static function authorizedToCreate(Request $request)
    {
        return false;
    }
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\Aan::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'id';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id',
        'value',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            Date::make('Date', 'created_at')
                ->exceptOnForms()
                ->sortable(),
            Text::make('Value')
                ->sortable()
                ->rules(['required', 'unique:aans,value,{{resourceId}}']),
            BelongsTo::make('User', 'user', User::class),
            BelongsTo::make('Generated by', 'generator', User::class),
            Badge::make('Status')
                ->map([
                    (self::$model)::NOT_USED => 'danger',
                    (self::$model)::USED => 'success',
                ]),
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function lenses(Request $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        $registrationLink = url("/scholars/register");
        $message = "
        <p>Greetings, __________!</p>
        <br>
        <br>
        <p>Thank you so much for joining BRUnity, the ever-growing BRUMultiverse family of creatives! As you have already signed your contract with us, we’re pleased to inform you that you are now ready to create your BRU Scholar Account. 
        
       </p>
       <br>
       <p>
         To begin, please take note of your Awarded Account Number (AAN): _______________.
        </p>
        <br>
        <p>
        Your AAN is uniquely yours. Please do not lose or allow others to use it, as everything related to your masterpieces for digital publishing will be linked to it. 
        </p>
        
        <br>
        <p>
        Let’s start your journey by clicking this link: 
        <a href='$registrationLink'>$registrationLink</a>
        <br>
        <p>
        Should you have questions, please feel free to email us at bru.admin@brumultiverse.com or within the BRU App via messaging, once your account is up. 
        </p>
        Have a great day!
        <br>
        <br>
        <p>
        Antonina
        </p>
        <p>
        Berkeley-Reagan University Admin
        </p>
        <p>
        BRUMultiverse
        </p>";
        return [
            (new GenerateNewAan)
                ->standalone(),
            (new SendEmail(false, $message))
                ->standalone(), 
        ];
    }
}
